import type { ExploreCourse, ExploreCoursesData } from "@/lib/trainer-service"

const fallbackCategories: ExploreCoursesData["categories"] = [
  { id: "all", name: "الكل" },
  { id: "tech", name: "Tech & Programming" },
  { id: "data", name: "Data Science & AI" },
  { id: "design", name: "Design & Creativity" },
  { id: "business", name: "Business & Marketing" },
]

const fallbackCourses: ExploreCourse[] = [
  {
    id: "fallback-course-1",
    trainerId: null,
    instituteId: null,
    title: "Full-Stack Web Development Bootcamp",
    description:
      "Comprehensive web development course covering frontend and backend technologies, databases, and deployment.",
    shortDescription: "Learn full-stack development from scratch",
    category: "Tech & Programming",
    image: "/images/course-web.png",
    studentsCount: 18,
    sessionsCount: 12,
    duration: 12,
    trainer: { name: "Dr. Khaled Rahman", avatar: null },
    price: 500,
    minStudents: 5,
    courseStatus: "ACTIVE",
    startDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    deliveryType: "online",
    roomId: null,
    roomName: null,
  },
  {
    id: "fallback-course-2",
    trainerId: null,
    instituteId: null,
    title: "Machine Learning Fundamentals",
    description:
      "Introduction to machine learning concepts, algorithms, and practical applications using Python.",
    shortDescription: "Learn ML from the ground up",
    category: "Data Science & AI",
    image: "/images/course-web.png",
    studentsCount: 14,
    sessionsCount: 10,
    duration: 10,
    trainer: { name: "Prof. Amina Abdullah", avatar: null },
    price: 600,
    minStudents: 3,
    courseStatus: "ACTIVE",
    startDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    deliveryType: "online",
    roomId: null,
    roomName: null,
  },
  {
    id: "fallback-course-3",
    trainerId: null,
    instituteId: null,
    title: "UI/UX Design Masterclass",
    description: "Complete guide to user interface and user experience design with hands-on projects.",
    shortDescription: "Master UI/UX design",
    category: "Design & Creativity",
    image: "/images/course-web.png",
    studentsCount: 12,
    sessionsCount: 8,
    duration: 8,
    trainer: { name: "Dr. Nadia Yousef", avatar: null },
    price: 450,
    minStudents: 4,
    courseStatus: "ACTIVE",
    startDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    deliveryType: "online",
    roomId: null,
    roomName: null,
  },
  {
    id: "fallback-course-4",
    trainerId: null,
    instituteId: null,
    title: "Digital Marketing Strategy",
    description: "Learn how to create and execute effective digital marketing campaigns.",
    shortDescription: "Master digital marketing",
    category: "Business & Marketing",
    image: "/images/course-web.png",
    studentsCount: 21,
    sessionsCount: 6,
    duration: 6,
    trainer: { name: "Prof. Tariq Saeed", avatar: null },
    price: 350,
    minStudents: 5,
    courseStatus: "ACTIVE",
    startDate: new Date().toISOString(),
    createdAt: new Date().toISOString(),
    deliveryType: "online",
    roomId: null,
    roomName: null,
  },
]

export function getFallbackExploreData(): ExploreCoursesData {
  return {
    courses: fallbackCourses,
    categories: fallbackCategories,
  }
}
